# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals DESKTOP-0K46F98

stages:
- stage: deploy_stage
  displayName: terraform stage
  jobs:
  - job: deploy_job
    displayName: terraform job
    steps:
    - task: TerraformInstaller@1
      displayName: terraform install
      inputs:
       terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: terraform init
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/src/terraform'
        backendServiceAWS: 'TerraformAWS'
        backendAWSBucketName: 'terraform-sy'
        backendAWSKey: 'tf/terraform.tfstate'
    - task: TerraformTaskV4@4
      displayName: terraform apply
      inputs:
        provider: 'aws'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/src/terraform'
        environmentServiceNameAWS: 'TerraformAWS'